# Generated by Selenium IDE
import pytest
import time
import json
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestloginok():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testloginok(self):
    self.driver.get("http://127.0.0.1:5000/auth/login")
    self.driver.set_window_size(1234, 841)
    self.driver.find_element(By.NAME, "email").send_keys("admin1@test.ch")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Abc$123")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "Benvenuto, admin1!"
    self.driver.save_screenshot(f'{sys._getframe().f_code.co_name}.png') # generates a png file with the name of the test function being called
  
